[[headers]]
  for = "/assets/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"