[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=2678400"
[[headers]]
  for = "/ja/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=2678400"
[[headers]]
  for = "/zh-Hans/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=2678400"
[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=2678400"