// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */

import products from './src/products/products';

const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  // tutorialSidebar: [
  //   'intro',
  //   'hello',
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['tutorial-basics/create-a-document'],
  //   },
  // ]
  tutorialSidebar: [
    ...Object.keys(products).map((name) => {
      const product = products[name];
      if (product.versions !== undefined) {
        return {
            type: "category",
            label: name,
            link: {
              type: "doc",
              id: `${name}/index`
            },
            items: [...product.versions.map((version) => `${name}/versions/${version}/index`)]
          }
      } else {
        return `${name}/index`;
      }
    })
  ]
};

export default sidebars;
